import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: "#FFFFFF",
        justifyContent: "center",
        alignItems: "center",
    },
    boxTop: {
        marginBottom: 40,
        alignItems: "center",
    },
    title: {
        fontSize: 32,
        fontWeight: "bold",
        color: "#1B5E20",
        textAlign: "center",
        marginBottom: 16,
    },
    boxMid: {
        width: "100%",
        alignItems: "center",
        marginBottom: 40,
    },
    titleInput: {
        fontSize: 20,
        fontWeight: "600",
        color: "#388E3C",
        marginBottom: 8,
        textAlign: "center",
    },
    boxInput: {
        backgroundColor: "#A5D6A7",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginBottom: 16,
        width: "85%",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
    },
    input: {
        fontSize: 18,
        color: "#1B5E20",
        width: "100%",
        textAlign: "center",
        fontFamily: "Roboto",
    },
    boxBottom: {
        width: "100%",
        alignItems: "center",
    },
    button: {
        backgroundColor: "#4CAF50",
        paddingVertical: 14,
        paddingHorizontal: 30,
        borderRadius: 12,
        width: "70%",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
    },
    buttonText: {
        color: "#E8F5E9",
        fontWeight: "bold",
        fontSize: 18,
    },
    modalContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
        width: "90%",
        backgroundColor: "#81C784",
        borderRadius: 16,
        padding: 20,
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#1B5E20",
        marginBottom: 24,
        textAlign: "center",
    },
    listItem: {
        paddingVertical: 14,
        paddingHorizontal: 18,
        backgroundColor: "#A5D6A7",
        borderRadius: 12,
        marginBottom: 12,
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
    },

    listItemText: {
        fontSize: 20,
        color: "#1B5E20",
        fontWeight: "500",
        textAlign: "center",
        width: "100%",
        paddingHorizontal: 15,
    },
    modalCloseButton: {
        marginTop: 24,
        backgroundColor: "#388E3C",
        paddingVertical: 14,
        paddingHorizontal: 30,
        borderRadius: 12,
        alignItems: "center",
        width: "60%",
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
    },
    modalCloseText: {
        color: "#E8F5E9",
        fontWeight: "bold",
        fontSize: 18,
    },
});
